// Silknet — core adapter contract.
//
// This file is the single source of truth for the ProviderAdapter interface
// defined in the build brief. Adapters, the service worker, and the dev test
// console all import from here so the contract cannot drift between them.

/** idle / generating / done / blocked / unknown */
export type AdapterState = 'idle' | 'generating' | 'done' | 'blocked' | 'unknown';

export interface ProbeResult {
  recognized: boolean;
  /** whether the tab has zero conversation turns (clean/empty pre-run check) */
  isClean?: boolean;
  /** why not recognized, for the diagnostic dot */
  reason?: string;
}

export interface CompletionResult {
  complete: boolean;
  /** e.g. ["response-stable-1800ms", "stop-control-absent", "composer-ready"] */
  reason: string[];
}

export interface AdapterCapabilities {
  autoSend: boolean;
  manualSend: boolean;
  readReply: boolean;
  completionDetectionMethods: string[];
  inputType: 'textarea' | 'contenteditable';
}

export interface SubmitResult {
  /** Generated by the adapter/orchestrator at call time (NOT derived from
   *  anything on the page). Explicit link between "what was sent" and "which
   *  reply belongs to it". */
  submissionId: string;
  /** True when the adapter itself dispatched the send (AUTO mode). SEMI mode
   *  leaves the send to a human and returns false. */
  autoSent: boolean;
}

export interface ProviderAdapter {
  /** Run BEFORE a debate starts, so a broken selector fails immediately and
   *  visibly, not 90 seconds into a run. */
  probe(): Promise<ProbeResult>;
  getState(): Promise<AdapterState>;
  /** Check if the conversation is completely empty/clean for Round 0 peer-blindness */
  isClean(): boolean;
  submit(text: string, opts?: { autoSend?: boolean }): Promise<SubmitResult>;
  waitForCompletion(
    submissionId: string,
    opts?: { timeoutMs?: number },
  ): Promise<CompletionResult>;
  readReply(submissionId: string): Promise<string>;
  /** Re-establishes RPC binding after content script invalidation
   *  (e.g. user refreshed the tab). */
  recover(): Promise<void>;
  capabilities(): AdapterCapabilities;
}

/**
 * Binds an operation to provider + tabId + frameId + document identity.
 *
 * A "provider + tab ID" binding alone has a time-of-check-to-time-of-use gap:
 * the tab can navigate away between a URL check and the action that follows
 * it. Every operation carries a DocumentIdentity so a post-navigation call is
 * rejected outright rather than silently acting on a different document.
 */
export interface DocumentIdentity {
  provider: string;
  tabId: number;
  frameId: number;
  /** Per-document nonce (crypto.randomUUID) regenerated on every real load.
   *  A refresh therefore changes this value, which is what detects TOCTOU. */
  documentId: string;
  href: string;
  origin: string;
}
